// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	auth2 "quest-admin/internal/biz/auth"
	organization2 "quest-admin/internal/biz/organization"
	permission2 "quest-admin/internal/biz/permission"
	tenant2 "quest-admin/internal/biz/tenant"
	user2 "quest-admin/internal/biz/user"
	"quest-admin/internal/conf"
	"quest-admin/internal/data/auth"
	"quest-admin/internal/data/data"
	"quest-admin/internal/data/idgen"
	"quest-admin/internal/data/organization"
	"quest-admin/internal/data/permission"
	"quest-admin/internal/data/pg"
	"quest-admin/internal/data/redis"
	"quest-admin/internal/data/tenant"
	"quest-admin/internal/data/transaction"
	"quest-admin/internal/data/user"
	"quest-admin/internal/server"
	auth3 "quest-admin/internal/service/auth"
	organization3 "quest-admin/internal/service/organization"
	permission3 "quest-admin/internal/service/permission"
	tenant3 "quest-admin/internal/service/tenant"
	user3 "quest-admin/internal/service/user"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	db := pg.NewDB(bootstrap)
	dataData := data.NewData(db)
	userRepo := user.NewUserRepo(dataData, logger)
	manager := transaction.NewManager(db)
	idGenerator := idgen.NewIDGenerator()
	userDeptRepo := user.NewUserDeptRepo(dataData, logger)
	userPostRepo := user.NewUserPostRepo(dataData, logger)
	userRoleRepo := user.NewUserRoleRepo(dataData, logger)
	userUsecase := user2.NewUserUsecase(logger, userRepo, manager, idGenerator, userDeptRepo, userPostRepo, userRoleRepo)
	roleRepo := permission.NewRoleRepo(dataData, logger)
	roleMenuRepo := permission.NewRoleMenuRepo(dataData, logger)
	roleUsecase := permission2.NewRoleUsecase(manager, idGenerator, roleRepo, roleMenuRepo, logger)
	departmentRepo := organization.NewDepartmentRepo(dataData, logger)
	departmentUsecase := organization2.NewDepartmentUsecase(idGenerator, departmentRepo, logger)
	postRepo := organization.NewPostRepo(dataData, logger)
	postUsecase := organization2.NewPostUsecase(idGenerator, postRepo, logger)
	userService := user3.NewUserService(userUsecase, roleUsecase, departmentUsecase, postUsecase, logger)
	grpcServer := server.NewGRPCServer(bootstrap, logger, userService)
	client := redis.NewRedis(bootstrap)
	authManager := auth.NewAuthManager(client)
	tenantRepo := tenant.NewTenantRepo(dataData, logger)
	tenantUsecase := tenant2.NewTenantUsecase(tenantRepo, logger)
	tenantPackageRepo := tenant.NewTenantPackageRepo(dataData, logger)
	tenantPackageUsecase := tenant2.NewTenantPackageUsecase(tenantPackageRepo, logger)
	tenantService := tenant3.NewTenantService(tenantUsecase, tenantPackageUsecase, logger)
	roleService := permission3.NewRoleService(roleUsecase, logger)
	menuRepo := permission.NewMenuRepo(dataData, logger)
	menuUsecase := permission2.NewMenuUsecase(idGenerator, menuRepo, logger)
	menuService := permission3.NewMenuService(menuUsecase, logger)
	departmentService := organization3.NewDepartmentService(departmentUsecase, logger)
	postService := organization3.NewPostService(postUsecase, logger)
	authUsecase := auth2.NewAuthUsecase(authManager, logger, userUsecase, roleUsecase, menuUsecase)
	authService := auth3.NewAuthService(logger, authUsecase, userUsecase, roleUsecase, menuUsecase)
	httpServer := server.NewHTTPServer(bootstrap, logger, authManager, userService, tenantService, roleService, menuService, departmentService, postService, authService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
